In [1]:
import pandas as pd

In [10]:
import os

mapping_file = pd.ExcelFile(os.path.join( 'metadata', 'vietnames_to_fiin.xlsx'))

In [16]:
df_bs = mapping_file.parse('Standard BS')[['Universal_caption', 'universal_code']]
df_is = mapping_file.parse('Standard IS')[['Universal_caption', 'universal_code']]
df_cf = mapping_file.parse('Standard CF')[['Universal_caption', 'universal_code']]

In [17]:
df_bs = df_bs.rename(columns={'Universal_caption': 'category_name', 'universal_code': 'category_code'})
df_is = df_is.rename(columns={'Universal_caption': 'category_name', 'universal_code': 'category_code'})
df_cf = df_cf.rename(columns={'Universal_caption': 'category_name', 'universal_code': 'category_code'})

df_map_fs = pd.concat([df_bs, df_is, df_cf], ignore_index=True)

df_map_fs.to_csv(os.path.join('metadata', 'map_category_code.csv'), index=False)

In [6]:
df = pd.read_parquet('../../data/financial_statement_v3.parquet')

In [7]:
df

            data stock_code  quarter    year date_added category_code
0       3253.384        BID      0.0  2010.0 2010-12-30          None
1       3628.604        BID      0.0  2011.0 2011-12-30          None
2       3295.068        BID      0.0  2012.0 2012-12-30          None
3       3862.664        BID      0.0  2013.0 2013-12-30          None
4       5393.484        BID      0.0  2014.0 2014-12-30          None
...          ...        ...      ...     ...        ...           ...
296384  1747.000        DGC      3.0  2024.0 2024-09-30        IS_140
296385  1849.000        DGC      4.0  2024.0 2024-12-30        IS_140
296386  2003.000        DGC      1.0  2025.0 2025-03-30        IS_140
296387  2085.000        DGC      2.0  2025.0 2025-06-30        IS_140
296388  1860.000        DGC      3.0  2025.0 2025-09-30        IS_140

[296389 rows x 6 columns]

In [5]:
df[df['category_code'] == 'IS_090']

,data,stock_code,quarter,year,date_added,universal_code_x,universal_code_y,category_code
720,0.000000,SSI,0.0,2010.0,2010-12-30,None,None,IS_090
721,0.000000,SSI,0.0,2011.0,2011-12-30,None,None,IS_090
722,0.000000,SSI,0.0,2012.0,2012-12-30,None,None,IS_090
723,0.000000,SSI,0.0,2013.0,2013-12-30,None,None,IS_090
724,-183.144865,SSI,0.0,2014.0,2014-12-30,None,None,IS_090
...,...,...,...,...,...,...,...,...
157085,-61.995634,DGC,3.0,2024.0,2024-09-30,None,None,IS_090
157086,-79.776846,DGC,4.0,2024.0,2024-12-30,None,None,IS_090
157087,-141.122729,DGC,1.0,2025.0,2025-03-30,None,None,IS_090
157088,-95.468665,DGC,2.0,2025.0,2025-06-30,None,None,IS_090
157089,-96.897791,DGC,3.0,2025.0,2025-09-30,None,None,IS_090